spring.application.name=eventnode-api

# =====================================================
# CONEXIÓN A BASE DE DATOS (usando Docker)
# =====================================================
spring.datasource.url=jdbc:mysql://localhost:3307/event_node?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=vixo_dev
spring.datasource.password=eventnode01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================
# JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# SERVER
# =====================================================
server.port=8080

# =====================================================
# LOGGING
# =====================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE