spring.application.name=eventnode-api

# =====================================================
# CONEXI�N A BASE DE DATOS (usando Docker)
# =====================================================
spring.datasource.url=jdbc:mysql://localhost:3307/event_node?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=vixo_dev
spring.datasource.password=eventnode01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================
# JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# SERVER
# =====================================================
server.port=8080

# Tamaño máximo de petición (necesario para banners Base64)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =====================================================
# JACKSON (serialización/deserialización JSON)
# =====================================================
spring.jackson.serialization.write-dates-as-timestamps=false

# =====================================================
# MAIL (Gmail SMTP)
# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=caszn06@gmail.com
spring.mail.password=fsvj hnby ammv jueo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =====================================================
# LOGGING
# =====================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE