services:
  mysql:
    image: mysql:8.0
    container_name: event_node_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rooteventnode01
      MYSQL_DATABASE: event_node
      MYSQL_USER: vixo_dev
      MYSQL_PASSWORD: eventnode01
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eventos_network

  backend:
    build:
      context: ../backend/eventnode-api
      dockerfile: Dockerfile
    container_name: event_node_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/event_node?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: vixo_dev
      SPRING_DATASOURCE_PASSWORD: eventnode01
    depends_on:
      - mysql
    networks:
      - eventos_network

  frontend:
    build:
      context: ../web-app
      dockerfile: Dockerfile
    container_name: event_node_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eventos_network

volumes:
  mysql_data:

networks:
  eventos_network:
    driver: bridge
